<a href="https://colab.research.google.com/github/Kalpesh-lab/Pandas/blob/Learnings/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [28]:
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], columns =["A", "B", "C"], index = ['x', 'y', 'z','zz'])

In [29]:
df

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [30]:
df.head()

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [36]:
df.tail()

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [32]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, x to zz
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

In [25]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [34]:
df['A'].unique()

array([ 1,  4,  7, 10])

In [35]:
df.shape

(4, 3)